import { Lib } from '@rnr/reusables';

export const { NAV_THEME } = Lib;

export const COMPONENTS = [
  'accordion',
  'alert',
  'alert-dialog',
  'avatar',
  'badge',
  'bottom-navigation',
  'bottom-sheet',
  'button',
  'calendar',
  'card',
  'checkbox',
  'context-menu',
  'data-table',
  'date-picker',
  'dialog',
  'dropdown-menu',
  'hover-card',
  'illustration',
  'input',
  'phone-input',
  'label',
  'material-top-tabs',
  'menubar',
  'navigation-menu',
  'progress',
  'radio-group',
  'select',
  'separator',
  'skeleton',
  'slider',
  'switch',
  'table',
  'textarea',
  'toast',
  'toggle-group',
  'tooltip',
  'typography',
];

// export const PRIMITIVES = [
//   'accordion',
//   'alert-dialog',
//   'aspect-ratio',
//   'avatar',
//   'checkbox',
//   'collapsible',
//   'context-menu',
//   'dialog',
//   'dropdown-menu',
//   'hover-card',
//   'label',
//   'menubar',
//   'navigation-menu',
//   'popover',
//   'portal',
//   'progress',
//   'radio-group',
//   'select',
//   'separator',
//   'slider',
//   'switch',
//   'table',
//   'tabs',
//   'toast',
//   'toggle',
//   'toggle-group',
//   'toolbar',
//   'tooltip',
// ];
