const { hairlineWidth } = require('nativewind/theme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  fontFamily: { fontName: 'Inter' },
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './node_modules/@rnr/**/*.{ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        error: {
          DEFAULT: 'hsl(var(--error))',
          foreground: 'hsl(var(--error-foreground))',
        },
        success: {
          DEFAULT: 'hsl(var(--success))',
          foreground: 'hsl(var(--success-foreground))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
          foreground: 'hsl(var(--warning-foreground))',
        },
        info: {
          DEFAULT: 'hsl(var(--info))',
          foreground: 'hsl(var(--info-foreground))',
        },
        ref: {
          secondary: {
            950: 'hsl(var(--ref-secondary-950) / <alpha-value>)',
            900: 'hsl(var(--ref-secondary-900) / <alpha-value>)',
            800: 'hsl(var(--ref-secondary-800) / <alpha-value>)',
            700: 'hsl(var(--ref-secondary-700) / <alpha-value>)',
            600: 'hsl(var(--ref-secondary-600) / <alpha-value>)',
            500: 'hsl(var(--ref-secondary-500) / <alpha-value>)',
            400: 'hsl(var(--ref-secondary-400) / <alpha-value>)',
            300: 'hsl(var(--ref-secondary-300) / <alpha-value>)',
            200: 'hsl(var(--ref-secondary-200) / <alpha-value>)',
            100: 'hsl(var(--ref-secondary-100) / <alpha-value>)',
            50: 'hsl(var(--ref-secondary-50) / <alpha-value>)',
          },
          neutral: {
            950: 'hsl(var(--ref-neutral-950) / <alpha-value>)',
            900: 'hsl(var(--ref-neutral-900) / <alpha-value>)',
            800: 'hsl(var(--ref-neutral-800) / <alpha-value>)',
            700: 'hsl(var(--ref-neutral-700) / <alpha-value>)',
            600: 'hsl(var(--ref-neutral-600) / <alpha-value>)',
            500: 'hsl(var(--ref-neutral-500) / <alpha-value>)',
            400: 'hsl(var(--ref-neutral-400) / <alpha-value>)',
            300: 'hsl(var(--ref-neutral-300) / <alpha-value>)',
            200: 'hsl(var(--ref-neutral-200) / <alpha-value>)',
            100: 'hsl(var(--ref-neutral-100) / <alpha-value>)',
            50: 'hsl(var(--ref-neutral-50) / <alpha-value>)',
          },
          information: {
            950: 'hsl(var(--ref-information-950) / <alpha-value>)',
            900: 'hsl(var(--ref-information-900) / <alpha-value>)',
            800: 'hsl(var(--ref-information-800) / <alpha-value>)',
            700: 'hsl(var(--ref-information-700) / <alpha-value>)',
            600: 'hsl(var(--ref-information-600) / <alpha-value>)',
            500: 'hsl(var(--ref-information-500) / <alpha-value>)',
            400: 'hsl(var(--ref-information-400) / <alpha-value>)',
            300: 'hsl(var(--ref-information-300) / <alpha-value>)',
            200: 'hsl(var(--ref-information-200) / <alpha-value>)',
            100: 'hsl(var(--ref-information-100) / <alpha-value>)',
            50: 'hsl(var(--ref-information-50) / <alpha-value>)',
          },
          success: {
            950: 'hsl(var(--ref-success-950) / <alpha-value>)',
            900: 'hsl(var(--ref-success-900) / <alpha-value>)',
            800: 'hsl(var(--ref-success-800) / <alpha-value>)',
            700: 'hsl(var(--ref-success-700) / <alpha-value>)',
            600: 'hsl(var(--ref-success-600) / <alpha-value>)',
            500: 'hsl(var(--ref-success-500) / <alpha-value>)',
            400: 'hsl(var(--ref-success-400) / <alpha-value>)',
            300: 'hsl(var(--ref-success-300) / <alpha-value>)',
            200: 'hsl(var(--ref-success-200) / <alpha-value>)',
            100: 'hsl(var(--ref-success-100) / <alpha-value>)',
            50: 'hsl(var(--ref-success-50) / <alpha-value>)',
          },
          warning: {
            950: 'hsl(var(--ref-warning-950) / <alpha-value>)',
            900: 'hsl(var(--ref-warning-900) / <alpha-value>)',
            800: 'hsl(var(--ref-warning-800) / <alpha-value>)',
            700: 'hsl(var(--ref-warning-700) / <alpha-value>)',
            600: 'hsl(var(--ref-warning-600) / <alpha-value>)',
            500: 'hsl(var(--ref-warning-500) / <alpha-value>)',
            400: 'hsl(var(--ref-warning-400) / <alpha-value>)',
            300: 'hsl(var(--ref-warning-300) / <alpha-value>)',
            200: 'hsl(var(--ref-warning-200) / <alpha-value>)',
            100: 'hsl(var(--ref-warning-100) / <alpha-value>)',
            50: 'hsl(var(--ref-warning-50) / <alpha-value>)',
          },
          error: {
            950: 'hsl(var(--ref-error-950) / <alpha-value>)',
            900: 'hsl(var(--ref-error-900) / <alpha-value>)',
            800: 'hsl(var(--ref-error-800) / <alpha-value>)',
            700: 'hsl(var(--ref-error-700) / <alpha-value>)',
            600: 'hsl(var(--ref-error-600) / <alpha-value>)',
            500: 'hsl(var(--ref-error-500) / <alpha-value>)',
            400: 'hsl(var(--ref-error-400) / <alpha-value>)',
            300: 'hsl(var(--ref-error-300) / <alpha-value>)',
            200: 'hsl(var(--ref-error-200) / <alpha-value>)',
            100: 'hsl(var(--ref-error-100) / <alpha-value>)',
            50: 'hsl(var(--ref-error-50) / <alpha-value>)',
          },
          'service-card': {
            light: 'hsl(var(--ref-service-card-light) / <alpha-value>)',
            dark: 'hsl(var(--ref-service-card-dark) / <alpha-value>)',
          },
          scrim: {
            light: 'hsl(var(--ref-scrim-light) / <alpha-value>)',
            dark: 'hsl(var(--ref-scrim-dark) / <alpha-value>)',
          },
        },

        
        sys: {
          'surface-neutral': {
            0: 'hsl(var(--sys-surface-neutral-0) / <alpha-value>)',
            1: 'hsl(var(--sys-surface-neutral-1) / <alpha-value>)',
            2: 'hsl(var(--sys-surface-neutral-2) / <alpha-value>)',
            3: 'hsl(var(--sys-surface-neutral-3) / <alpha-value>)',
            4: 'hsl(var(--sys-surface-neutral-4) / <alpha-value>)',
            5: 'hsl(var(--sys-surface-neutral-5) / <alpha-value>)',
          },
          'surface-disabled': 'hsl(var(--sys-surface-disabled) / <alpha-value>)',
          'surface-scrim': 'hsl(var(--sys-surface-scrim) / <alpha-value>)',
          'surface-card': 'hsl(var(--sys-surface-card) / <alpha-value>)',
          'surface-black': 'hsl(var(--sys-surface-black) / <alpha-value>)',
          'surface-white': 'hsl(var(--sys-surface-white) / <alpha-value>)',
          'secondary-pressed': 'hsl(var(--sys-secondary-pressed) / <alpha-value>)',
          'surface-secondary': {
            1: 'hsl(var(--sys-surface-secondary-1) / <alpha-value>)',
            2: 'hsl(var(--sys-surface-secondary-2) / <alpha-value>)',
            3: 'hsl(var(--sys-surface-secondary-3) / <alpha-value>)',
            4: 'hsl(var(--sys-surface-secondary-4) / <alpha-value>)',
            5: 'hsl(var(--sys-surface-secondary-5) / <alpha-value>)',
          },
          fn: {
            generic: 'hsl(var(--sys-fn-generic) / <alpha-value>)',
            error: 'hsl(var(--sys-fn-error) / <alpha-value>)',
            'error-text': 'hsl(var(--sys-fn-error-text) / <alpha-value>)',
            success: 'hsl(var(--sys-fn-success) / <alpha-value>)',
            'success-text': 'hsl(var(--sys-fn-success-text) / <alpha-value>)',
            warning: 'hsl(var(--sys-fn-warning) / <alpha-value>)',
            'warning-text': 'hsl(var(--sys-fn-warning-text) / <alpha-value>)',
            information: 'hsl(var(--sys-fn-information) / <alpha-value>)',
            'information-text': 'hsl(var(--sys-fn-information-text) / <alpha-value>)',
          },
          text: {
            white: 'hsl(var(--sys-text-white) / <alpha-value>)',
            black: 'hsl(var(--sys-text-black) / <alpha-value>)',
            body: 'hsl(var(--sys-text-body) / <alpha-value>)',
            'body-inverse': 'hsl(var(--sys-text-body-inverse) / <alpha-value>)',
            secondary: 'hsl(var(--sys-text-secondary) / <alpha-value>)',
            neutral: {
              1: 'hsl(var(--sys-text-neutral-1) / <alpha-value>)',
              2: 'hsl(var(--sys-text-neutral-2) / <alpha-value>)',
              3: 'hsl(var(--sys-text-neutral-3) / <alpha-value>)',
              4: 'hsl(var(--sys-text-neutral-4) / <alpha-value>)',
            },
            disabled: 'hsl(var(--sys-text-disabled) / <alpha-value>)',
            alt: 'hsl(var(--sys-alt-text) / <alpha-value>)',
            subhead: 'hsl(var(--sys-subhead-text) / <alpha-value>)',
          },
          border: {
            1: 'hsl(var(--sys-border-1) / <alpha-value>)',
            2: 'hsl(var(--sys-border-2) / <alpha-value>)',
            3: 'hsl(var(--sys-border-3) / <alpha-value>)',
            4: 'hsl(var(--sys-border-4) / <alpha-value>)',
            5: 'hsl(var(--sys-border-5) / <alpha-value>)',
            6: 'hsl(var(--sys-border-6) / <alpha-value>)',
            information: 'hsl(var(--sys-border-information) / <alpha-value>)',
            success: 'hsl(var(--sys-border-success) / <alpha-value>)',
            warning: 'hsl(var(--sys-border-warning) / <alpha-value>)',
            error: 'hsl(var(--sys-border-error) / <alpha-value>)',
            default: 'hsl(var(--sys-border-default) / <alpha-value>)',
          },
          appbg: 'hsl(var(--sys-appbg) / <alpha-value>)',
          radio: 'hsl(var(--sys-radio) / <alpha-value>)',
          form: {
            default: 'hsl(var(--sys-form-default) / <alpha-value>)',
            disabled: 'hsl(var(--sys-form-disabled) / <alpha-value>)',
            error: 'hsl(var(--sys-form-error) / <alpha-value>)',
            success: 'hsl(var(--sys-form-success) / <alpha-value>)',
            active: 'hsl(var(--sys-form-active) / <alpha-value>)',
          },
          divider: {
            decorative: 'hsl(var(--sys-divider-decorative) / <alpha-value>)',
            default: 'hsl(var(--sys-divider-default) / <alpha-value>)',
          },
          scrim: 'hsl(var(--sys-scrim) / <alpha-value>)',
          focus: 'hsl(var(--sys-focus) / <alpha-value>)',

        },
      },
      fontSize: {
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['14px', { lineHeight: '20px' }],
        base: ['15px', { lineHeight: '20px' }],
        md: ['16px', { lineHeight: '23px' }],
        lg: ['22px', { lineHeight: '28px' }],
        xl: ['26px', { lineHeight: '28px' }],
        '2xl': ['15px', { lineHeight: '15px' }],
        '3xl': ['17px', { lineHeight: '36px' }],
        '4xl': ['20px', { lineHeight: '45px' }],
        '5xl': ['24px', { lineHeight: '45px' }],
        '6xl': ['32px', { lineHeight: '45px' }],
        '7xl': ['36px', { lineHeight: '45px' }],
        '8xl': ['40px', { lineHeight: '45px' }],
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
        'xs-8': 'var(--xs---8)',
        'sm-12': 'var(--sm---12)',
        'md-16': 'var(--md---16)',
        'lg-24': 'var(--lg---24)',
      },
      borderRadius: {
        none: '0',
        xs: '4px',
        sm: '8px',
        DEFAULT: '8px',
        md: '12px',
        lg: '24px',
        xl: '32px',
        '2xl': '40px',
        '3xl': '50px',
        '4xl': '60px',
        full: '999px',
      },
      borderWidth: {
        hairline: hairlineWidth(),
        0: 'var(--border-width-0)',
        sm: 'var(--border-width-sm)',
        md: 'var(--border-width-md)',
        lg: 'var(--border-width-lg)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};